disk-cache=5M
file-allocation=none
continue=true
max-concurrent-downloads=5
max-connection-per-server=15
min-split-size=10M
split=5
disable-ipv6=true
check-certificate=false
allow-overwrite=true
auto-file-renaming=false
